const DishesData = [
  {
    id: "1",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÚN BÒ",
    time: "1h 41m",
    calo: 350,
    likes: 1000,
    rating: 3,
  },
  {
    id: "2",
    type: "Side dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "GỎI CUỐN",
    time: "30m",
    calo: 150,
    likes: 1000,
    rating: 4.2,
  },
  {
    id: "3",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "PHỞ BÒ",
    time: "2h",
    calo: 400,
    likes: 1000,
    rating: 5,
  },
  {
    id: "4",
    type: "Dessert",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CHÈ BƯỞI",
    time: "1h",
    calo: 250,
    likes: 1000,
    rating: 4.5,
  },
  {
    id: "5",
    type: "Lunch",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "NEM RÁN",
    time: "45m",
    calo: 300,
    likes: 1000,
    rating: 3.8,
  },
  {
    id: "6",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CƠM TẤM",
    time: "1h 15m",
    calo: 550,
    likes: 1000,
    rating: 4.9,
  },
  {
    id: "7",
    type: "Dessert",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH FLAN",
    time: "1h 10m",
    calo: 200,
    likes: 800,
    rating: 4.7,
  },
  {
    id: "8",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH XÈO",
    time: "1h",
    calo: 500,
    likes: 900,
    rating: 4.3,
  },
  {
    id: "9",
    type: "Snack",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH MÌ",
    time: "15m",
    calo: 250,
    likes: 1500,
    rating: 4.8,
  },
  {
    id: "10",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH CANH",
    time: "2h",
    calo: 450,
    likes: 1200,
    rating: 4.6,
  },
  {
    id: "11",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH KHỌT",
    time: "1h",
    calo: 300,
    likes: 1000,
    rating: 4.2,
  },
  {
    id: "12",
    type: "Side dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CHẢ GIÒ",
    time: "30m",
    calo: 350,
    likes: 900,
    rating: 4.5,
  },
  {
    id: "13",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "MIẾN GÀ",
    time: "45m",
    calo: 300,
    likes: 1000,
    rating: 4.4,
  },
  {
    id: "14",
    type: "Dessert",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH TRÔI",
    time: "30m",
    calo: 150,
    likes: 1200,
    rating: 4.8,
  },
  {
    id: "15",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "LẨU MẮM",
    time: "2h",
    calo: 600,
    likes: 1000,
    rating: 4.9,
  },
  {
    id: "16",
    type: "Lunch",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CƠM GÀ HẢI NAM",
    time: "1h 30m",
    calo: 550,
    likes: 800,
    rating: 4.3,
  },
  {
    id: "17",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "LẨU THÁI",
    time: "1h 45m",
    calo: 700,
    likes: 1300,
    rating: 4.9,
  },
  {
    id: "18",
    type: "Dessert",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH DÀY",
    time: "1h",
    calo: 200,
    likes: 700,
    rating: 4.2,
  },
  {
    id: "19",
    type: "Side dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CHẢ CÁ",
    time: "30m",
    calo: 350,
    likes: 1100,
    rating: 4.5,
  },
  {
    id: "20",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH CUỐN",
    time: "1h",
    calo: 400,
    likes: 1000,
    rating: 4.6,
  },
  {
    id: "21",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH ĐÚC",
    time: "1h",
    calo: 250,
    likes: 900,
    rating: 4.1,
  },
  {
    id: "22",
    type: "Snack",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH RÁN",
    time: "20m",
    calo: 220,
    likes: 1400,
    rating: 4.8,
  },
  {
    id: "23",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÚN CHẢ",
    time: "1h 30m",
    calo: 500,
    likes: 1200,
    rating: 4.7,
  },
  {
    id: "24",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CANH CHUA",
    time: "1h",
    calo: 350,
    likes: 1000,
    rating: 4.4,
  },
  {
    id: "25",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "LẨU CUA",
    time: "1h 50m",
    calo: 700,
    likes: 1000,
    rating: 4.6,
  },
  {
    id: "26",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH BÈO",
    time: "45m",
    calo: 200,
    likes: 800,
    rating: 4.3,
  },
  {
    id: "27",
    type: "Snack",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH QUY",
    time: "1h 20m",
    calo: 150,
    likes: 1200,
    rating: 4.7,
  },
  {
    id: "28",
    type: "Dessert",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "KEM BƠ",
    time: "20m",
    calo: 250,
    likes: 900,
    rating: 4.8,
  },
  {
    id: "29",
    type: "Lunch",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CƠM GÀ LUỘC",
    time: "45m",
    calo: 500,
    likes: 1000,
    rating: 4.5,
  },
  {
    id: "30",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÚN RIÊU",
    time: "1h",
    calo: 400,
    likes: 1100,
    rating: 4.6,
  },
  {
    id: "31",
    type: "Snack",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH GIÒ",
    time: "30m",
    calo: 300,
    likes: 800,
    rating: 4.2,
  },
  {
    id: "32",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "MIẾN LƯƠN",
    time: "1h",
    calo: 400,
    likes: 1000,
    rating: 4.4,
  },
  {
    id: "33",
    type: "Side dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CHẢ MỰC",
    time: "30m",
    calo: 350,
    likes: 1200,
    rating: 4.6,
  },
  {
    id: "34",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "LẨU HẢI SẢN",
    time: "2h",
    calo: 700,
    likes: 1300,
    rating: 4.9,
  },
  {
    id: "35",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH ƯỚT",
    time: "1h",
    calo: 250,
    likes: 900,
    rating: 4.3,
  },
  {
    id: "36",
    type: "Snack",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH BAO",
    time: "1h 30m",
    calo: 450,
    likes: 1100,
    rating: 4.5,
  },
  {
    id: "37",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÚN ĐẬU MẮM TÔM",
    time: "45m",
    calo: 400,
    likes: 1500,
    rating: 4.7,
  },
  {
    id: "38",
    type: "Dessert",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH PÍA",
    time: "1h",
    calo: 300,
    likes: 800,
    rating: 4.2,
  },
  {
    id: "39",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH TRÁNG TRỘN",
    time: "15m",
    calo: 250,
    likes: 1400,
    rating: 4.8,
  },
  {
    id: "40",
    type: "Side dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "NEM NƯỚNG",
    time: "1h",
    calo: 400,
    likes: 1000,
    rating: 4.6,
  },
  {
    id: "41",
    type: "Lunch",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "CƠM CHIÊN",
    time: "30m",
    calo: 500,
    likes: 900,
    rating: 4.4,
  },
  {
    id: "42",
    type: "Snack",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "KHOAI LANG CHIÊN",
    time: "20m",
    calo: 200,
    likes: 1200,
    rating: 4.7,
  },
  {
    id: "43",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH CANH CUA",
    time: "1h 30m",
    calo: 600,
    likes: 1300,
    rating: 4.8,
  },
  {
    id: "44",
    type: "Dessert",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH RÁN VỪNG",
    time: "30m",
    calo: 250,
    likes: 1000,
    rating: 4.5,
  },
  {
    id: "45",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH NẬM",
    time: "45m",
    calo: 200,
    likes: 800,
    rating: 4.1,
  },
  {
    id: "46",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÚN BÒ HUẾ",
    time: "1h 30m",
    calo: 550,
    likes: 1500,
    rating: 4.9,
  },
  {
    id: "47",
    type: "Snack",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÁNH PHỒNG TÔM",
    time: "10m",
    calo: 150,
    likes: 900,
    rating: 4.3,
  },
  {
    id: "48",
    type: "Main dish",
    img: "https://i.ibb.co/kxVPqYg/bunbo.png",
    name: "BÚN MẮM",
    time: "2h",
    calo: 500,
    likes: 1100,
    rating: 4.8,
  },
];

export default DishesData;
