export const addedMeals = [
  {
    id: 1,
    name: "Bánh chuối yến mạch ngâm qua đêm",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 2,
    name: "Bánh chuối yến mạch ngâm qua đêm",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 3,
    name: "Bánh chuối yến mạch ngâm qua đêm",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 4,
    name: "Bánh chuối yến mạch ngâm qua đêm",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 5,
    name: "Bánh chuối yến mạch ngâm qua đêm 5",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 6,
    name: "Bánh chuối yến mạch ngâm qua đêm 6",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 7,
    name: "Bánh chuối yến mạch ngâm qua đêm 7",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 8,
    name: "Bánh chuối yến mạch ngâm qua đêm 8",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 9,
    name: "Bánh chuối yến mạch ngâm qua đêm 5",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 10,
    name: "Bánh chuối yến mạch ngâm qua đêm 6",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 11,
    name: "Bánh chuối yến mạch ngâm qua đêm 5",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
  {
    id: 12,
    name: "Bánh chuối yến mạch ngâm qua đêm 6",
    weight: "300g",
    calories: 350,
    carb: 10,
    protein: 10,
    fat: 10,
  },
];
export const systemMeals = [
  {
    id: 1,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 2,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 3,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 4,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 5,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 6,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 7,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 8,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
  {
    id: 9,
    name: "Chả nấm kho tiêu",
    image: "https://i.ibb.co/kxVPqYg/bunbo.png",
    weight: "150g",
    protein: 10,
    fat: 10,
    carb: 10,
    calo: 300,
  },
];
export const userMeals = [
  {
    id: 1,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 2,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 3,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 4,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 5,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 6,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 7,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 8,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
  {
    id: 9,
    name: "Bánh mì trứng",
    image: "/banhmitrung.png",
    weight: "200g",
    protein: 12,
    fat: 15,
    carb: 50,
    calo: 400,
  },
];
