const workoutsData = [
  {
    id: "1",
    name: "Bài tập khởi động 1",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 30,
    calo: 10,
    rating: 5,
  },
  {
    id: "2",
    name: "Bài tập khởi động 2",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 15,
    calo: 12,
    rating: 4,
  },
  {
    id: "3",
    name: "Bài tập khởi động 3",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 20,
    calo: 8,
    rating: 3,
  },
  {
    id: "4",
    name: "Bài tập khởi động 4",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 25,
    calo: 9,
    rating: 2,
  },
  {
    id: "5",
    name: "Bài tập khởi động 5",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 45,
    calo: 14,
    rating: 1,
  },
  {
    id: "6",
    name: "Bài tập khởi động 6",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 50,
    calo: 7,
    rating: 5,
  },
  {
    id: "7",
    name: "Bài tập khởi động 7",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 40,
    calo: 11,
    rating: 4,
  },
  {
    id: "8",
    name: "Bài tập khởi động 8",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 35,
    calo: 13,
    rating: 3,
  },
  {
    id: "9",
    name: "Bài tập khởi động 9",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 28,
    calo: 10,
    rating: 2,
  },
  {
    id: "10",
    name: "Bài tập khởi động 10",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 55,
    calo: 6,
    rating: 1,
  },
  {
    id: "11",
    name: "Bài tập khởi động 11",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 22,
    calo: 8,
    rating: 5,
  },
  {
    id: "12",
    name: "Bài tập khởi động 12",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 33,
    calo: 12,
    rating: 4,
  },
  {
    id: "13",
    name: "Bài tập khởi động 13",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 48,
    calo: 9,
    rating: 3,
  },
  {
    id: "14",
    name: "Bài tập khởi động 14",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 18,
    calo: 11,
    rating: 2,
  },
  {
    id: "15",
    name: "Bài tập khởi động 15",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 27,
    calo: 5,
    rating: 1,
  },
  {
    id: "16",
    name: "Bài tập khởi động 16",
    image: "https://i.ibb.co/x1K7stB/workout-1.png",
    time: 24,
    calo: 15,
    rating: 5,
  },
];

export default workoutsData;
